import Navigation from "./components/navigation";
import "./styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Mi primer app </title>
      </head>

      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
