import Navigation from "./components/navigation";
import "./styles/globals.css";
import { font } from "./font.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>La socialApp de blogs :D</title>
      </head>

      <body className={font.variable}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
